### ISSUE TITLE
Interfacing with C: CFFI

### ISSUE THREAD

**Issue by westurner** [scipy-lectures/scipy-lecture-notes#131] opened 2015-02-19 19:53 UTC
A section on Interfacing with C through **CFFI** would be useful, both for CPython and for PyPy.

https://github.com/scipy-lectures/scipy-lecture-notes/edit/master/advanced/interfacing_with_c/interfacing_with_c.rst
- Docs: https://cffi.readthedocs.org/en/latest/
- PyPI: https://pypi.python.org/pypi/cffi
- Src: hg+ https://bitbucket.org/cffi/cffi

**Comment by esc** [comment] 2015-02-19 22:49
Duplicate of: https://github.com/scipy-lectures/scipy-lecture-notes/issues/87

But thanks for raising this again, maybe the time has come.

**Comment by westurner** [comment] 2015-02-19 23:06
This is Python-based CFFI, which is notable and relevant.

From http://pypy.org/compat.html :

> PyPy has alpha/beta-level support for the CPython C API, however, this feature is not yet complete. We strongly advise use of CFFI instead. CFFI come builtin with PyPy. Many libraries will require a bit of effort to work, but there are known success stories. Check out PyPy blog for updates, as well as the Compatibility Wiki.

**Comment by esc** [comment] 2015-02-28 18:19
If anyone has bandwidth for this, feel free to submit a PR!

**Comment by vahtras** [comment] 2018-03-16 11:31
I agree. This is an awesome library and anyone with time to write such a section is welcome to do so.

**Comment by astrojuanlu** [comment] 2023-06-09 09:11
So happy to see this repo coming back to life ❤️ Was this guide written? I can't seem to find it in the repo

**Comment by stefanv** [comment] 2023-06-10 06:09
@astrojuanlu Sorry, the issue should have been closed as "not planned", not "completed". I don't know of a lot of usage of CFFI in the scientific ecosystem, so I don't know if such a lesson is warranted or where we would get someone to write it.

Perhaps a better lesson to add nowadays is Pythran?

Happy to hear your thoughts, though!

**Closed** 2023-06-10 06:09 UTC

**Comment by esc** [comment] 2023-06-10 09:01
How about Numba 😁 ?

**Comment by westurner** [comment] 2023-06-11 03:30
-
https://github.com/apache/arrow/blob/main/python/pyarrow/tests/test_cffi.py

-
https://arrow.apache.org/docs/python/pandas.html#memory-usage-and-zero-copy

- `engine="pyarrow"`
https://pandas.pydata.org/docs/user_guide/pyarrow.html#i-o-reading

- https://en.wikipedia.org/wiki/Foreign_function_interface

- https://en.wikipedia.org/wiki/Libffi :
  > libffi is most often used as a bridging technology between compiled and
interpreted language implementations. libffi may also be used to implement
plug-ins, where the plug-in's function signatures are not known at the time
of creating the host application.
  > Notable users include Python, Haskell, Dalvik, F-Script, PyPy, PyObjC,
RubyCocoa, JRuby, Rubinius, MacRuby, gcj, GNU Smalltalk, IcedTea, Cycript,
Pawn, Squeak, Java Native Access, Common Lisp (via CFFI), Racket,[2]
Embeddable Common Lisp and Mozilla.[3]
