### ISSUE TITLE
SEC: https://scipy-lectures.org

### ISSUE THREAD

**Issue by westurner** [scipy-lectures/scipy-lecture-notes#409] opened 2019-01-26 01:13 UTC
When I access https://scipy-lectures.org (over HTTPS) I get a cert error.

GitHub Pages now supports HTTPS on custom domains (with https://letsencrypt.org/) 
https://github.blog/2018-05-01-github-pages-custom-domains-https/

https://help.github.com/articles/securing-your-github-pages-site-with-https/

https://help.github.com/articles/troubleshooting-custom-domains/#https-errors

**Comment by pdebuyl** [comment] 2019-01-27 13:38
Thank you for notice @westurner 

I disabled the custom domain and re-enabled it, which is recommended in the instructions of GitHub. Things should be ok in one hour, if not we'll have to look at our DNS settings. (The extended comment is also intended as a record for the other maintainers of the notes). Our internal links are relative, so I just hope this will not require other changes.

Regards,

Pierre

**Comment by pdebuyl** [comment] 2019-01-27 13:50
The "unsafe" warning disappeared for me. I'll close the issue if this is confirmed by others.

P

**Comment by westurner** [comment] 2019-01-27 17:00
https://www.ssllabs.com/ssltest/analyze.html?d=scipy-lectures.org
-  Sun, 27 Jan 2019 16:59:00 UTC
  "Certificate name mismatch"

**Comment by pdebuyl** [comment] 2019-01-27 17:50
The certificates are only valid for the `www` subdomain. The plain (no `www`) domain does not redirect properly. The tests for `www.scipy-lectures.org` are good: https://www.ssllabs.com/ssltest/analyze.html?d=www.scipy%2dlectures.org&ignoreMismatch=on&latest

@GaelVaroquaux are you managing the DNS record for scipy-lectures.org ? If so, can you enable a direct redirect of `scipy-lectures.org` to `www.scipy-lectures.org`? GitHub only allows a single domain name for the SSL certificates.

**Comment by westurner** [comment] 2019-01-27 21:50
It should work with a naked (www.-less) domain (A records); but then you'd need a redirect for existing www. links.

- [ ] http://scipy-lectures.org -> https://www.
- HSTS avoids further non-HTTPS redirects
  - CloudFlare does HTTPS redirects and HSTS

- [ ] https://scipy-lectures.org -> https://www.

**Comment by GaelVaroquaux** [comment] 2019-01-27 21:55
OK, I'll try to work this out, but DNS is incomprehensible to me, and I
must say that I am terrified to touch the configuration.

**Comment by GaelVaroquaux** [comment] 2019-01-27 22:01
@pdebuyl : I don't know how to do a redirect.

Also: is to possible to redirect the www to the non www URL? I personally don't really like the "www". It makes the url longer for no good reason.

**Comment by westurner** [comment] 2019-01-28 00:31
https://help.github.com/articles/about-supported-custom-domains/

https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/

> Warning: If your domain has HTTPS enforcement enabled, GitHub Pages'
servers will not automatically route redirects. You must configure www
subdomain and root domain redirects with your domain registrar.

(Or e.g. CloudFlare, which does free HTTPS redirects)

https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

> I looks like the option "Always use HTTPS" is not served as a page rule
anymore.
> I found this option under the Crypto tab.

**Comment by westurner** [comment] 2019-01-28 00:35
https://help.github.com/articles/about-supported-custom-domains/

https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/

> Warning: If your domain has HTTPS enforcement enabled, GitHub Pages'
servers will not automatically route redirects. You must configure www
subdomain and root domain redirects with your domain registrar.

(Or e.g. CloudFlare, which does free HTTPS redirects)

https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

> I looks like the option "Always use HTTPS" is not served as a page rule
anymore.
> I found this option under the Crypto tab.

**Comment by GaelVaroquaux** [comment] 2019-01-28 08:33
How do I do step 2 (the redirection)?

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by pdebuyl** [comment] 2019-01-28 08:36
There is a tab in the settings, at the same level as "enregistrements dns", where you can add redirects.

**Comment by GaelVaroquaux** [comment] 2019-01-28 10:30
> There is a tab in the settings, at the same level as "enregistrements dns", where you can add redirects.

I am not sure what you are talking about. On the Ghandi interface, I have
no "settings" tab, and nothing that looks like "enregistrements dns" (or
the English version). The Ghandi interface allows me to add entries to
the DNS records: "A" entries, "CNAME", and the like.

I've added a "CNAME", which after googling seems to be redirect in DNS
(but honestly, I am clueless with DNS). I've deployed the DNS
configuration.

Right now, we are getting a certificate failure in HTTPS. Hopefully it is
because the DNS records have not propagated.

**Comment by pdebuyl** [comment] 2019-01-28 10:39
DNS timeout is 3 hours for `scipy-lectures.org`, and GitHub delay for propagating certificates is estimated at 1 hour. We'll have to wait some time anyway :-)

The CNAME is an alias, not a redirect, so the failure will remain. Let's wait for the timeouts (at 14:30) before evaluating.

I sent you an email with a screenshot of the gandi panel to make sure we are on the same page.

**Comment by GaelVaroquaux** [comment] 2019-01-28 11:03
OK, it seems that I had to change Gandi version and hence transfer the domain handling to new DNS servers to enable the redirection. I did that (I definitely feels like the sorcerer's apprentice). Now we need to wait for everything to propagate.

**Comment by pdebuyl** [comment] 2019-01-28 11:39
The new interface allows dns setup "by record", I find it much easier. I am definitely not expert on DNS but we should be able to manage this :-)

Did you setup also the redirection?

**Comment by GaelVaroquaux** [comment] 2019-01-28 11:59
I did setup up the redirect (call "forwarding" in the new interface). They told me that they needed to migrate the configuration to new servers for the redirect to work, and that it could take 24H. Let's see what happens.

**Comment by westurner** [comment] 2019-01-28 13:04
AFAIU, this means that there is now an HTTP but not an HTTPS redirect?

**Comment by pdebuyl** [comment] 2019-01-28 13:11
Whenever the setup works correctly, we can add extra redirects via the dns provider. All http to https, for instance (i.e. for both www and non-www urls). Do we want to enforce all https?

**Comment by westurner** [comment] 2019-01-28 14:07
All HTTPS is the least risk for this sensitive material.

Does your DNS provider do HTTPS redirects? It'd need to generate SSL certs
for each domain with e.g. https://letsencrypt.org, just like GitHub and
CloudFlare.

I've emailed GitHub about just handling www. HTTPS redirects hopefully by
just optionally requesting the www. and Apex domain in the cert request
(and the cert subjectAltNames). IDK if that's possible (wildcard domain
certs now are) or when or whether it might be implemented.

**Comment by GaelVaroquaux** [comment] 2019-01-28 14:17
> All HTTPS is the least risk for this sensitive material.

Except HTTPS is always broken due to certificates issues. I understand
the logic behind all this, but right now the whole thing is just terribly
fragile.

> Does your DNS provider do HTTPS redirects?

I think so, but I understand little to all this.

> It'd need to generate SSL certs for each domain with e.g.
> https://letsencrypt.org, just like GitHub and CloudFlare.

Following the instructions on Github pages, I've just deleted and
recreated our CNAME instruction on Github. They mention that this can be
necessary to trigger the update of the certificate.

I did it right now. Let's see if it solves the problem. I see two steps:
first getting it to work for the non www address (which should be solved
by my operation above, maybe in an hours). Second: getting the redirect
to work. This should be fixed by my operation on the DNS provider. But,
because apparently they need to migrate to a new DNS server, it might
take longer, as long as 24H.

**Comment by GaelVaroquaux** [comment] 2019-01-28 14:19
> I did it right now. Let's see if it solves the problem. I see two steps: first getting it to work for the non www address (which should be solved by my operation above, maybe in an hours).

Update: https://scipy-lectures.org/ now works! Hopefully this is not a
transitory status while some error that I've made is still propagating
through the system.

**Comment by GaelVaroquaux** [comment] 2019-01-28 14:20
Hum, looks like both work.

Can people confirm?

Once again, I hope that we have no surprise lingering in an unpropagated
change. I understand nothing of this wizardry.

**Comment by pdebuyl** [comment] 2019-01-28 15:46
The `https://www.scipy-lectures.org` to `https://scipy-lectures.org` redirect works now in one of my browsers. Maybe still a caching issue.

**Comment by pdebuyl** [comment] 2019-01-28 16:06
Now both my browsers resolve all the links and go to the non www version.

http remains http and https remains https

To me, we can leave it so. @westurner you seem to push for "all https", but in the lecture notes the code seems pretty innocent (small snippets, and mostly copy-pasted). Am I being simplistic here?

**Comment by westurner** [comment] 2019-01-28 16:08
Still getting connection reset from here. I'll check again in a few hours.
Thanks for addressing this

**Comment by GaelVaroquaux** [comment] 2019-01-28 16:15
> To me, we can leave it so. @westurner you seem to push for "all https", but in the lecture notes the code seems pretty innocent (small snippets, and mostly copy-pasted). Am I being simplistic here?

I think that the issue is that HTTP leave the door open to man in the
middle attack. For instance an ISP, or a government, injecting tracking
code in webpages. This has been done in the past, so the question is a
real one.

However, I'd rather wait for the dust to settle down on our HTTPS serving
before enforcing it (I am a bit traumatized by DNS :D ).

**Comment by GaelVaroquaux** [comment] 2019-01-29 06:44
OK, I'm closing this issue, and we can revisit later the idea of redirecting HTTP to HTTPS.

**Closed by GaelVaroquaux** 2019-01-29 06:44 UTC
